version: '3.8'

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001' 
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  node-temp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: node-temp
    restart: always
    privileged: true
    depends_on:
      - mosquitto